---
- hosts: "{{ cli_nsxm_group | default('nsxm_global') }}"
  connection: local
  gather_facts: no

  vars:
    federation_role: global

  vars_files:
    - ../../vars/passwords.yml
    - ../../vars/mongodb_settings.yml

  tasks:

    - name: Set password
      set_fact:
        password: "{{ passwords[inventory_hostname][username] }}"

    - name: Pull in the data for all defined group paths in the nsx-t manager
      set_fact:
        group_paths: "{{ [mongo_connection, 'group_paths' ] | read_from_mongodb}}"

    - name: Retrieve the defined domains ( regions ) for the NSX-T manager
      vmware.ansible_for_nsxt.nsxt_policy_domain_info:
        hostname: "{{ inventory_hostname }}"
        "username": "{{ username }}"
        "password": "{{ password }}"
        validate_certs: False
        federation_role: global
      register: nsxt_domain_info
      delegate_to: 127.0.0.1

    - name: Just pull out the ids from the nsxt_domain_info data
      set_fact:
        domain_ids: "{{ nsxt_domain_info | json_query('results[].id')}}"

    - name: Loop using these domain paths to get all of the group info
      vmware.ansible_for_nsxt.nsxt_policy_group_info:
        hostname: "{{ inventory_hostname }}"
        "username": "{{ username }}"
        "password": "{{ password }}"
        validate_certs: False
        federation_role: global
        domain_id: "{{ domain_id }}"
        #page_size: 10
      register: nsxt_all_group_info
      delegate_to: 127.0.0.1
      loop: "{{ domain_ids }}"
      loop_control:
        loop_var: domain_id

    - name: Just pull out the groups from the nsxt_domain_info data
      set_fact:
        group_data: "{{ nsxt_all_group_info | json_query('results[].results[].{display_name: display_name, path: path, expression: expression}')}}"

    - name: Write the data to mongodb for filter_testing
      set_fact: "{{ [mongo_connection, group_data, 'group_data'] | write_to_mongodb }}"
      tags: [ filter_testing ]

    #- meta: end_play

    - name: Run a filter to look for broken group references in group expressions
      set_fact:
        group_reference_problems: "{{ [group_data, group_paths] | find_broken_group_refs }}"

    - debug:
        var: group_reference_problems